/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IzinIslem;

import arayuz.islemler;
import java.awt.Component;
import java.awt.HeadlessException;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author geronimo
 */
public class kullyeniIzi extends javax.swing.JFrame {

    /**
     * Creates new form yeniIzin
     */
     public kullyeniIzi() {
        initComponents();
        
        kayitNoOtomatikAl();
        sicilNoComboboxDuzenle();
    }

    veritabani.baglanti vb = new veritabani.baglanti();
    public Statement baglantiAc() throws SQLException {
        
        try {
            Class.forName(vb.DRIVER).newInstance();
            vb.con = DriverManager.getConnection(vb.URL + vb.DB_NAME, vb.ID, vb.PW);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Veritabanı Bağlantı Hatası!!!\n" + e);
        }
        return vb.con.createStatement();
    }
    
    public void baglantiKapat() throws SQLException {
        vb.con.close();
    }
    
    private void kayitNoOtomatikAl() {
        
        try {
            
            Statement s = baglantiAc();
            String sql = "SELECT kayit_no FROM izin ORDER BY kayit_no DESC LIMIT 1";
            
            ResultSet rs = s.executeQuery(sql);
            
            String kayitNo = "";
            while(rs.next()) {
                kayitNo = rs.getString("kayit_no");
            }
            baglantiKapat();
            
            txt_kayitno.setText(Integer.toString(Integer.parseInt(kayitNo) + 1));
            
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Kayıt No Bulunurken Hata Meydana Geldi!!!\n" + e);
        }
    }
    
    private void sicilNoComboboxDuzenle() {
          try {
            Statement c=baglantiAc();
            String sql="SELECT DISTINCT izin_turu FROM izin";
            
            ResultSet rs= c.executeQuery(sql);
            while (rs.next()) {
                izin_türü.addItem(rs.getString("izin_turu"));
                }
            baglantiKapat();
            
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "izin türü bulmak için "
                    + "veritabanına bağlanırken bir hata meydana geldi!!!\n" + e);
        }
      
      
       try {
            
            Statement s = baglantiAc();
            
            String sql = "SELECT sicil_no FROM personel";
           
            
            ResultSet rs = s.executeQuery(sql);
            
            
            while(rs.next()) {
                scl_cmb.addItem( rs.getObject("sicil_no"));
               
            }
            baglantiKapat();
            
            
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Sicil No bulmak için "
                    + "veritabanına bağlanırken bir hata meydana geldi!!!\n" + e);
        }
    }
  
    
    private void yeniIzinVer() {
        
        try {
            
                    YeniIzinEkle izin = new YeniIzinEkle(txt_birim.getText(), txt_kayitno.getText(),
                    scl_cmb.getSelectedItem().toString(), kalanizinmiktari_txt.getText(),
                    izinbastarih_txt.getText(), izinbittarih_txt.getText(),
                    izin_türü.getSelectedItem().toString(), kullizinmik_txt.getText());
            
            boolean durum = izin.izinVer(izin);
            if(durum) {
                txt_kayitno.setText(Integer.toString(Integer.parseInt(txt_kayitno.getText()) + 1));
                JOptionPane.showMessageDialog(null, "Ekleme Başarıyla Tamamlandı.");
            } else
                JOptionPane.showMessageDialog(null, "Ekleme Yapılamadı!!!");
                
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Yeni İzin Verme Hatası!!!\n" + e);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_kayitno = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_birim = new javax.swing.JLabel();
        txt_birim = new javax.swing.JTextField();
        kalanizinmiktari_txt = new javax.swing.JTextField();
        izinbastarih_txt = new javax.swing.JTextField();
        izinbittarih_txt = new javax.swing.JTextField();
        kullizinmik_txt = new javax.swing.JTextField();
        scl_cmb = new javax.swing.JComboBox();
        btn_ekle = new javax.swing.JButton();
        btn_geri = new javax.swing.JButton();
        txt_kayitno = new javax.swing.JLabel();
        btn_çıkış = new javax.swing.JButton();
        izin_türü = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Yeni İzin");

        lbl_kayitno.setText("Kayıt No:");

        jLabel3.setText("Sicil  No:");

        jLabel4.setText("Kalan İzin Miktarı :");

        jLabel5.setText("İzin Başlangıç Tarihi:");

        jLabel6.setText("İzin Bitiş Tarihi");

        jLabel7.setText("İzin Türü");

        jLabel8.setText("Kullanılan İzin Miktarı:");

        lbl_birim.setText("Birim:");

        txt_birim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_birimActionPerformed(evt);
            }
        });

        kalanizinmiktari_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalanizinmiktari_txtActionPerformed(evt);
            }
        });

        scl_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scl_cmbActionPerformed(evt);
            }
        });

        btn_ekle.setText("Yeni İzin Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_geri.setText("Geri");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        txt_kayitno.setText("jLabel2");

        btn_çıkış.setText("Çıkış");
        btn_çıkış.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_çıkışActionPerformed(evt);
            }
        });

        izin_türü.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izin_türüActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_kayitno)
                                    .addComponent(lbl_birim))
                                .addGap(180, 180, 180)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_birim)
                                    .addComponent(scl_cmb, 0, 77, Short.MAX_VALUE)
                                    .addComponent(txt_kayitno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(izinbittarih_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                            .addComponent(izinbastarih_txt)
                                            .addComponent(kullizinmik_txt)
                                            .addComponent(izin_türü, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(113, 113, 113)
                                        .addComponent(kalanizinmiktari_txt))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_geri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_çıkış)
                        .addGap(1, 1, 1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_birim)
                    .addComponent(txt_birim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_kayitno)
                    .addComponent(txt_kayitno))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(scl_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kalanizinmiktari_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(izinbastarih_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(izin_türü, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kullizinmik_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(izinbittarih_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ekle)
                    .addComponent(btn_geri)
                    .addComponent(btn_çıkış))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kalanizinmiktari_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalanizinmiktari_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalanizinmiktari_txtActionPerformed

    private void txt_birimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_birimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_birimActionPerformed

    private void btn_çıkışActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_çıkışActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_çıkışActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        this.dispose();
        new kullaniciislemleri.kullaniciislemler().setVisible(true);
        
    }//GEN-LAST:event_btn_geriActionPerformed

    private void scl_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scl_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scl_cmbActionPerformed

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
yeniIzinVer();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void izin_türüActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izin_türüActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_izin_türüActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminyeniIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminyeniIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminyeniIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminyeniIzin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminyeniIzin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_geri;
    private javax.swing.JButton btn_çıkış;
    private javax.swing.JComboBox izin_türü;
    private javax.swing.JTextField izinbastarih_txt;
    private javax.swing.JTextField izinbittarih_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kalanizinmiktari_txt;
    private javax.swing.JTextField kullizinmik_txt;
    private javax.swing.JLabel lbl_birim;
    private javax.swing.JLabel lbl_kayitno;
    private javax.swing.JComboBox scl_cmb;
    private javax.swing.JTextField txt_birim;
    private javax.swing.JLabel txt_kayitno;
    // End of variables declaration//GEN-END:variables
}
